DROP TABLE Soldvia 		CASCADE CONSTRAINTS;
DROP TABLE Salestransaction 	CASCADE CONSTRAINTS;
DROP TABLE Store 		CASCADE CONSTRAINTS;
DROP TABLE Product 		CASCADE CONSTRAINTS;
DROP TABLE Vendor 		CASCADE CONSTRAINTS;
DROP TABLE Region 		CASCADE CONSTRAINTS;
DROP TABLE Category 		CASCADE CONSTRAINTS;
DROP TABLE Customer 		CASCADE CONSTRAINTS; 